/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CW3;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Enumeration;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.AbstractButton;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 30868
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hotels_buttonGroup = new javax.swing.ButtonGroup();
        Left_Panel = new javax.swing.JPanel();
        Map_image = new javax.swing.JLabel();
        Right_Panel = new javax.swing.JPanel();
        Info_panel = new javax.swing.JPanel();
        Hotel_selected_panel = new javax.swing.JPanel();
        You_have_chosen_label = new javax.swing.JLabel();
        Selected_hotel_label = new javax.swing.JLabel();
        Hotel1_jRadioButton = new javax.swing.JRadioButton();
        Hotel2_jRadioButton = new javax.swing.JRadioButton();
        Hotel3_jRadioButton = new javax.swing.JRadioButton();
        Hotel4_jRadioButton = new javax.swing.JRadioButton();
        Hotel5_jRadioButton = new javax.swing.JRadioButton();
        Name_panel = new javax.swing.JPanel();
        Name_Label = new javax.swing.JLabel();
        Name_text = new javax.swing.JTextField();
        name_warning_label = new javax.swing.JLabel();
        Phone_panel = new javax.swing.JPanel();
        Phone_Label = new javax.swing.JLabel();
        Phone_text = new javax.swing.JTextField();
        phone_warning_label = new javax.swing.JLabel();
        Rooms_panel = new javax.swing.JPanel();
        Rooms_Label = new javax.swing.JLabel();
        Rooms_jComboBox = new javax.swing.JComboBox<>();
        rooms_warning_label = new javax.swing.JLabel();
        Check_in_date_panel = new javax.swing.JPanel();
        Check_in_date_label = new javax.swing.JLabel();
        check_in_date_jComboBox = new javax.swing.JComboBox<>();
        check_in_date_warning_label = new javax.swing.JLabel();
        Nights_panel = new javax.swing.JPanel();
        Night_Label = new javax.swing.JLabel();
        Nights_jComboBox = new javax.swing.JComboBox<>();
        nights_warning_label = new javax.swing.JLabel();
        Check_out_date_panel = new javax.swing.JPanel();
        Check_out_date_label = new javax.swing.JLabel();
        check_out_date_jComboBox = new javax.swing.JComboBox<>();
        check_out_date_warning_label = new javax.swing.JLabel();
        Buttons_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Add_label = new javax.swing.JLabel();
        Add_button = new javax.swing.JButton();
        Reset_label = new javax.swing.JLabel();
        Reset_button = new javax.swing.JButton();
        Show_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        people_list = new javax.swing.JLabel();
        View_button = new javax.swing.JButton();
        Remove_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Reservation System");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1600, 1200));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1600, 1000));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        Left_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Map", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        Left_Panel.setToolTipText("");
        Left_Panel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        Left_Panel.setName(""); // NOI18N
        Left_Panel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        Left_Panel.setLayout(new java.awt.GridLayout(1, 0));

        Map_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CW3/Map.png"))); // NOI18N
        Map_image.setPreferredSize(new java.awt.Dimension(300, 300));
        Left_Panel.add(Map_image);

        getContentPane().add(Left_Panel);

        Right_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information Form", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        Right_Panel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        Right_Panel.setLayout(new java.awt.GridLayout(0, 1));

        Info_panel.setLayout(new java.awt.GridLayout(0, 1));

        Hotel_selected_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        You_have_chosen_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        You_have_chosen_label.setText("You have chosen :");
        Hotel_selected_panel.add(You_have_chosen_label);

        Selected_hotel_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Selected_hotel_label.setText("Hotel 1");
        Hotel_selected_panel.add(Selected_hotel_label);

        Hotels_buttonGroup.add(Hotel1_jRadioButton);
        Hotel1_jRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Hotel1_jRadioButton.setSelected(true);
        Hotel1_jRadioButton.setText("Hotel 1");
        Hotel1_jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hotel1_jRadioButtonActionPerformed(evt);
            }
        });
        Hotel_selected_panel.add(Hotel1_jRadioButton);

        Hotels_buttonGroup.add(Hotel2_jRadioButton);
        Hotel2_jRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Hotel2_jRadioButton.setText("Hotel 2");
        Hotel2_jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hotel2_jRadioButtonActionPerformed(evt);
            }
        });
        Hotel_selected_panel.add(Hotel2_jRadioButton);

        Hotels_buttonGroup.add(Hotel3_jRadioButton);
        Hotel3_jRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Hotel3_jRadioButton.setText("Hotel3");
        Hotel3_jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hotel3_jRadioButtonActionPerformed(evt);
            }
        });
        Hotel_selected_panel.add(Hotel3_jRadioButton);

        Hotels_buttonGroup.add(Hotel4_jRadioButton);
        Hotel4_jRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Hotel4_jRadioButton.setText("Hotel 4");
        Hotel4_jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hotel4_jRadioButtonActionPerformed(evt);
            }
        });
        Hotel_selected_panel.add(Hotel4_jRadioButton);

        Hotels_buttonGroup.add(Hotel5_jRadioButton);
        Hotel5_jRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Hotel5_jRadioButton.setText("Hotel 5");
        Hotel5_jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hotel5_jRadioButtonActionPerformed(evt);
            }
        });
        Hotel_selected_panel.add(Hotel5_jRadioButton);

        Info_panel.add(Hotel_selected_panel);

        Name_panel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        Name_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Name_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name_Label.setText("Name  :");
        Name_panel.add(Name_Label);

        Name_text.setColumns(18);
        Name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_textActionPerformed(evt);
            }
        });
        Name_panel.add(Name_text);

        name_warning_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name_warning_label.setForeground(java.awt.Color.red);
        name_warning_label.setText("*, click 'Enter' after typing");
        Name_panel.add(name_warning_label);

        Info_panel.add(Name_panel);

        Phone_panel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        Phone_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Phone_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Phone_Label.setText("Phone :");
        Phone_panel.add(Phone_Label);

        Phone_text.setColumns(18);
        Phone_text.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                Phone_textInputMethodTextChanged(evt);
            }
        });
        Phone_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone_textKeyPressed(evt);
            }
        });
        Phone_panel.add(Phone_text);

        phone_warning_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phone_warning_label.setForeground(java.awt.Color.red);
        phone_warning_label.setText("*, click 'Enter' after typing");
        Phone_panel.add(phone_warning_label);

        Info_panel.add(Phone_panel);

        Rooms_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Rooms_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Rooms_Label.setText("Rooms :");
        Rooms_panel.add(Rooms_Label);

        Rooms_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rooms_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Number of Rooms:", "1", "2", "3", "4", "5" }));
        Rooms_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rooms_jComboBoxActionPerformed(evt);
            }
        });
        Rooms_panel.add(Rooms_jComboBox);

        rooms_warning_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rooms_warning_label.setForeground(java.awt.Color.red);
        rooms_warning_label.setText("*");
        Rooms_panel.add(rooms_warning_label);

        Info_panel.add(Rooms_panel);

        Check_in_date_panel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        Check_in_date_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Check_in_date_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Check_in_date_label.setText("Check-In Date   :");
        Check_in_date_panel.add(Check_in_date_label);

        check_in_date_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        check_in_date_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Check In Date",LocalDate.now().toString(),LocalDate.now().plusDays(1).toString(),LocalDate.now().plusDays(2).toString(),LocalDate.now().plusDays(3).toString(),LocalDate.now().plusDays(4).toString(),LocalDate.now().plusDays(5).toString(),LocalDate.now().plusDays(6).toString()}));
        check_in_date_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_in_date_jComboBoxActionPerformed(evt);
            }
        });
        Check_in_date_panel.add(check_in_date_jComboBox);

        check_in_date_warning_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        check_in_date_warning_label.setForeground(java.awt.Color.red);
        check_in_date_warning_label.setText("*");
        Check_in_date_panel.add(check_in_date_warning_label);

        Info_panel.add(Check_in_date_panel);

        Nights_panel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        Nights_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Night_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Night_Label.setText("Nights :");
        Nights_panel.add(Night_Label);

        Nights_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nights_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Number of Nights: ", "1", "2", "3", "4" }));
        Nights_jComboBox.setToolTipText("");
        Nights_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nights_jComboBoxActionPerformed(evt);
            }
        });
        Nights_panel.add(Nights_jComboBox);

        nights_warning_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nights_warning_label.setForeground(java.awt.Color.red);
        nights_warning_label.setText("*");
        Nights_panel.add(nights_warning_label);

        Info_panel.add(Nights_panel);

        Check_out_date_panel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        Check_out_date_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Check_out_date_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Check_out_date_label.setText("Check-Out Date :");
        Check_out_date_panel.add(Check_out_date_label);

        check_out_date_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        check_out_date_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Check Out Date",LocalDate.now().plusDays(1).toString(),LocalDate.now().plusDays(2).toString(),LocalDate.now().plusDays(3).toString(),LocalDate.now().plusDays(4).toString(),LocalDate.now().plusDays(5).toString(),LocalDate.now().plusDays(6).toString(),LocalDate.now().plusDays(7).toString(),LocalDate.now().plusDays(8).toString(),LocalDate.now().plusDays(9).toString(),LocalDate.now().plusDays(10).toString()}));
        check_out_date_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_out_date_jComboBoxActionPerformed(evt);
            }
        });
        Check_out_date_panel.add(check_out_date_jComboBox);

        check_out_date_warning_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        check_out_date_warning_label.setForeground(java.awt.Color.red);
        check_out_date_warning_label.setText("*");
        Check_out_date_panel.add(check_out_date_warning_label);

        Info_panel.add(Check_out_date_panel);

        Buttons_panel.setMaximumSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("* ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Means Complusory Information");

        Add_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Add_label.setText("Add");

        Add_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Add_button.setText("Add");
        Add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_buttonActionPerformed(evt);
            }
        });

        Reset_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reset_label.setText("Reset");

        Reset_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Reset_button.setText("Reset");
        Reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Buttons_panelLayout = new javax.swing.GroupLayout(Buttons_panel);
        Buttons_panel.setLayout(Buttons_panelLayout);
        Buttons_panelLayout.setHorizontalGroup(
            Buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buttons_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Add_label)
                .addGap(18, 18, 18)
                .addComponent(Add_button)
                .addGap(18, 18, 18)
                .addComponent(Reset_label)
                .addGap(18, 18, 18)
                .addComponent(Reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        Buttons_panelLayout.setVerticalGroup(
            Buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buttons_panelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(Buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_button)
                    .addComponent(Add_label)
                    .addComponent(Reset_label)
                    .addComponent(Reset_button)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12))
        );

        Info_panel.add(Buttons_panel);

        Right_Panel.add(Info_panel);

        Show_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jScrollPane1.setViewportView(jList1);

        people_list.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        people_list.setText("Added Users");

        View_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        View_button.setText("View");
        View_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_buttonActionPerformed(evt);
            }
        });

        Remove_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Remove_button.setText("Remove");
        Remove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Show_panelLayout = new javax.swing.GroupLayout(Show_panel);
        Show_panel.setLayout(Show_panelLayout);
        Show_panelLayout.setHorizontalGroup(
            Show_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Show_panelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Show_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Remove_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(Show_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(people_list)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Show_panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Remove_button, View_button});

        Show_panelLayout.setVerticalGroup(
            Show_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Show_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(people_list)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Show_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Show_panelLayout.createSequentialGroup()
                        .addComponent(Remove_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(View_button)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        Show_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Remove_button, View_button});

        Right_Panel.add(Show_panel);

        getContentPane().add(Right_Panel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_textActionPerformed
        // TODO add your handling code here:
        Pattern p = Pattern.compile(".*\\d+.*");
        Matcher m = p.matcher(Name_text.getText());
        if (Name_text.getText().equals("")) {
            name_warning_label.setVisible(true);
        } else if (m.matches()) {
            name_warning_label.setVisible(true);
        } else {
            name_warning_label.setVisible(false);
        }
    }//GEN-LAST:event_Name_textActionPerformed

    private void Nights_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nights_jComboBoxActionPerformed
        // TODO add your handling code here:z
        if (Nights_jComboBox.getSelectedIndex() != 0) {
            if (check_in_date_jComboBox.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Please Select Check-In-Date First!", "WARNING", JOptionPane.WARNING_MESSAGE);
                Nights_jComboBox.setSelectedIndex(0);
                nights_warning_label.setVisible(true);
            } else {
                int nights = Integer.parseInt(Nights_jComboBox.getSelectedItem().toString());
                DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                LocalDate check_in_date = LocalDate.parse(check_in_date_jComboBox.getSelectedItem().toString(), df);
                LocalDate temp = check_in_date.plusDays(nights);
                check_out_date_jComboBox.setSelectedItem(temp.toString());
            }
            nights_warning_label.setVisible(false);
        } else {
            nights_warning_label.setVisible(true);
        }
    }//GEN-LAST:event_Nights_jComboBoxActionPerformed

    private void Reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_buttonActionPerformed
        // TODO add your handling code here:
        Name_text.setText("");
        Phone_text.setText("");
        name_warning_label.setVisible(true);
        phone_warning_label.setVisible(true);
        Nights_jComboBox.setSelectedIndex(0);
        Rooms_jComboBox.setSelectedIndex(0);
        check_in_date_jComboBox.setSelectedIndex(0);
        check_out_date_jComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_Reset_buttonActionPerformed

    private void Hotel1_jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hotel1_jRadioButtonActionPerformed
        // TODO add your handling code here:
        if (Hotel1_jRadioButton.isSelected()) {
            Selected_hotel_label.setText("Hotel 1");
        }
    }//GEN-LAST:event_Hotel1_jRadioButtonActionPerformed

    private void Hotel5_jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hotel5_jRadioButtonActionPerformed
        // TODO add your handling code here:
        if (Hotel5_jRadioButton.isSelected()) {
            Selected_hotel_label.setText("Hotel 5");
        }
    }//GEN-LAST:event_Hotel5_jRadioButtonActionPerformed

    private void Hotel2_jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hotel2_jRadioButtonActionPerformed
        // TODO add your handling code here:
        if (Hotel2_jRadioButton.isSelected()) {
            Selected_hotel_label.setText("Hotel 2");
        }
    }//GEN-LAST:event_Hotel2_jRadioButtonActionPerformed

    private void Hotel3_jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hotel3_jRadioButtonActionPerformed
        // TODO add your handling code here:
        if (Hotel3_jRadioButton.isSelected()) {
            Selected_hotel_label.setText("Hotel 3");
        }
    }//GEN-LAST:event_Hotel3_jRadioButtonActionPerformed

    private void Hotel4_jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hotel4_jRadioButtonActionPerformed
        // TODO add your handling code here:
        if (Hotel4_jRadioButton.isSelected()) {
            Selected_hotel_label.setText("Hotel 4");
        }
    }//GEN-LAST:event_Hotel4_jRadioButtonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        URL url = NewJFrame.class.getResource("Map.png");
        ImageIcon mapimage = new ImageIcon(url);
        Image img = mapimage.getImage();
        img = img.getScaledInstance(getWidth() / 2, getHeight() / 2, Image.SCALE_DEFAULT);
        mapimage.setImage(img);
        Map_image.setIcon(mapimage);
    }//GEN-LAST:event_formComponentResized

    private void Phone_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone_textKeyPressed
        // TODO add your handling code here:
        String phoneNumber = Phone_text.getText();
        Boolean flag = Pattern.matches("^1[3-9]\\d{9}$", phoneNumber);
        if (flag && (phoneNumber != null) && (!phoneNumber.isEmpty())) {
            phone_warning_label.setVisible(false);
        } else {
            phone_warning_label.setVisible(true);
        }
    }//GEN-LAST:event_Phone_textKeyPressed

    private void Phone_textInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Phone_textInputMethodTextChanged
        // TODO add your handling code here:
        String phoneNumber = Phone_text.getText();
        Boolean flag = Pattern.matches("^1[3-9]\\d{9}$", phoneNumber);
        if (flag && (phoneNumber != null) && (!phoneNumber.isEmpty())) {
            phone_warning_label.setVisible(false);

        } else {
            phone_warning_label.setVisible(true);
        }
    }//GEN-LAST:event_Phone_textInputMethodTextChanged

    private void Rooms_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rooms_jComboBoxActionPerformed
        // TODO add your handling code here:
        if (Rooms_jComboBox.getSelectedIndex() == 0) {
            rooms_warning_label.setVisible(true);
        } else {
            rooms_warning_label.setVisible(false);
        }
    }//GEN-LAST:event_Rooms_jComboBoxActionPerformed

    private void Add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_buttonActionPerformed
        // TODO add your handling code here:
        if (name_warning_label.isVisible() || phone_warning_label.isVisible() || check_in_date_warning_label.isVisible() || check_out_date_warning_label.isVisible() || nights_warning_label.isVisible() || rooms_warning_label.isVisible()) {
            JOptionPane.showMessageDialog(null, "Please Input all of information !", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else {
            String name = Name_text.getText();
            String phone = Phone_text.getText();
            String rooms = Rooms_jComboBox.getSelectedItem().toString();
            String night = Nights_jComboBox.getSelectedItem().toString();
            String check_in_date = check_in_date_jComboBox.getSelectedItem().toString();
            String check_out_date = check_out_date_jComboBox.getSelectedItem().toString();
            String hotel = "Unknown";

            Enumeration<AbstractButton> buttons = Hotels_buttonGroup.getElements();
            while (buttons.hasMoreElements()) {
                AbstractButton nextElement = buttons.nextElement();
                if (nextElement.isSelected()) {
                    hotel = nextElement.getText();
                    break;
                }
            }
            myPerson p = new myPerson(name, phone, night, rooms, check_in_date, check_out_date, hotel);
            if ((!name_warning_label.isVisible()) && (!phone_warning_label.isVisible()) && (!nights_warning_label.isVisible()) && (!rooms_warning_label.isVisible()) && (!check_in_date_warning_label.isVisible()) && (!check_out_date_warning_label.isVisible())) {
                myListModel.addElement(p);
                jList1.setModel(myListModel);
                Name_text.setText("");
                Phone_text.setText("");
                Nights_jComboBox.setSelectedIndex(0);
                Rooms_jComboBox.setSelectedIndex(0);
                check_in_date_jComboBox.setSelectedIndex(0);
                check_out_date_jComboBox.setSelectedIndex(0);
                name_warning_label.setVisible(true);
                phone_warning_label.setVisible(true);
                JOptionPane.showMessageDialog(null,
                        "Reserve Successfully !", "Success", JOptionPane.PLAIN_MESSAGE);
            }
        }

    }//GEN-LAST:event_Add_buttonActionPerformed

    private void View_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_buttonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jList1.getSelectedIndex();
        myPerson p = (myPerson) myListModel.getElementAt(selectedIndex);
        JOptionPane.showMessageDialog(null,
                "Hotel you choose :  " + p.getHotel()
                + "\nYour name is :  " + p.getName()
                + "\nYour phone is :  " + p.getPhone()
                + "\nNumber of rooms :  " + p.getRooms()
                + "\nNumber of nights :  " + p.getNights()
                + "\nCheck-In date :  " + p.getCheck_in_date()
                + "\nCheck-Out date :  " + p.getCheck_out_date(), "Information", JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_View_buttonActionPerformed

    private void check_in_date_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_in_date_jComboBoxActionPerformed
        // TODO add your handling code here:
        if (check_in_date_jComboBox.getSelectedIndex() != 0) {
            check_in_date_warning_label.setVisible(false);
            if (check_out_date_jComboBox.getSelectedIndex() != 0) {
                DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                LocalDate check_out_date = LocalDate.parse(check_out_date_jComboBox.getSelectedItem().toString(), df);
                LocalDate check_in_date = LocalDate.parse(check_in_date_jComboBox.getSelectedItem().toString(), df);
                Period next = Period.between(check_in_date, check_out_date);
                int days = next.getDays();
                if (days <= 0) {
                    JOptionPane.showMessageDialog(null, "Check Out date should behind Check In date !", "WARNING", JOptionPane.WARNING_MESSAGE);
                    check_out_date_jComboBox.setSelectedIndex(0);
                } else {
                    Nights_jComboBox.setSelectedItem(String.valueOf(days));
                }
            }

        } else {
            check_in_date_warning_label.setVisible(true);
        }
    }//GEN-LAST:event_check_in_date_jComboBoxActionPerformed

    private void check_out_date_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_out_date_jComboBoxActionPerformed
        // TODO add your handling code here:
        if (check_out_date_jComboBox.getSelectedIndex() != 0) {
            if (check_in_date_jComboBox.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Please Input Check-In-Date First!", "WARNING", JOptionPane.WARNING_MESSAGE);
                check_out_date_jComboBox.setSelectedIndex(0);
            } else {
                DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                LocalDate check_out_date = LocalDate.parse(check_out_date_jComboBox.getSelectedItem().toString(), df);
                LocalDate check_in_date = LocalDate.parse(check_in_date_jComboBox.getSelectedItem().toString(), df);
                Period next = Period.between(check_in_date, check_out_date);
                int days = next.getDays();
                if (days <= 0) {
                    check_out_date_warning_label.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Check Out date should behind Check In date !", "WARNING", JOptionPane.WARNING_MESSAGE);
                    check_out_date_jComboBox.setSelectedIndex(0);
                } else if (days > 4) {
                    check_out_date_warning_label.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Can not live more than 4 days !", "WARNING", JOptionPane.WARNING_MESSAGE);
                    check_out_date_jComboBox.setSelectedIndex(0);
                } else {
                    check_out_date_warning_label.setVisible(false);
                    Nights_jComboBox.setSelectedItem(String.valueOf(days));
                }
            }
        } else {
            check_out_date_warning_label.setVisible(true);
        }
    }//GEN-LAST:event_check_out_date_jComboBoxActionPerformed

    private void Remove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_buttonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jList1.getSelectedIndex();
        if (selectedIndex == -1) {
        } else {
            myListModel.remove(selectedIndex);
        }
    }//GEN-LAST:event_Remove_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);

            }
        });
    }
    DefaultListModel myListModel = new DefaultListModel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_button;
    private javax.swing.JLabel Add_label;
    private javax.swing.JPanel Buttons_panel;
    private javax.swing.JLabel Check_in_date_label;
    private javax.swing.JPanel Check_in_date_panel;
    private javax.swing.JLabel Check_out_date_label;
    private javax.swing.JPanel Check_out_date_panel;
    private javax.swing.JRadioButton Hotel1_jRadioButton;
    private javax.swing.JRadioButton Hotel2_jRadioButton;
    private javax.swing.JRadioButton Hotel3_jRadioButton;
    private javax.swing.JRadioButton Hotel4_jRadioButton;
    private javax.swing.JRadioButton Hotel5_jRadioButton;
    private javax.swing.JPanel Hotel_selected_panel;
    private javax.swing.ButtonGroup Hotels_buttonGroup;
    private javax.swing.JPanel Info_panel;
    private javax.swing.JPanel Left_Panel;
    private javax.swing.JLabel Map_image;
    private javax.swing.JLabel Name_Label;
    private javax.swing.JPanel Name_panel;
    private javax.swing.JTextField Name_text;
    private javax.swing.JLabel Night_Label;
    private javax.swing.JComboBox<String> Nights_jComboBox;
    private javax.swing.JPanel Nights_panel;
    private javax.swing.JLabel Phone_Label;
    private javax.swing.JPanel Phone_panel;
    private javax.swing.JTextField Phone_text;
    private javax.swing.JButton Remove_button;
    private javax.swing.JButton Reset_button;
    private javax.swing.JLabel Reset_label;
    private javax.swing.JPanel Right_Panel;
    private javax.swing.JLabel Rooms_Label;
    private javax.swing.JComboBox<String> Rooms_jComboBox;
    private javax.swing.JPanel Rooms_panel;
    private javax.swing.JLabel Selected_hotel_label;
    private javax.swing.JPanel Show_panel;
    private javax.swing.JButton View_button;
    private javax.swing.JLabel You_have_chosen_label;
    private javax.swing.JComboBox<String> check_in_date_jComboBox;
    private javax.swing.JLabel check_in_date_warning_label;
    private javax.swing.JComboBox<String> check_out_date_jComboBox;
    private javax.swing.JLabel check_out_date_warning_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name_warning_label;
    private javax.swing.JLabel nights_warning_label;
    private javax.swing.JLabel people_list;
    private javax.swing.JLabel phone_warning_label;
    private javax.swing.JLabel rooms_warning_label;
    // End of variables declaration//GEN-END:variables

}
